# Generated by Django 3.0.4 on 2020-03-31 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 3, 31)),
        ),
    ]
